#!/bin/sh
set -e
# Code generated by godownloader (raw mode) then patched for myagent goreleaser archives.
# Installs myagent from GitHub Releases: curl -fsSL https://raw.githubusercontent.com/AlvinPlayz23/myagent/main/install.sh | bash

usage() {
  this=$1
  cat <<EOF

$this: download binaries for AlvinPlayz23/myagent

Usage: $this [-b bindir] [-d] [tag]
  -b sets bindir or installation directory, Defaults to /usr/local/bin (or ~/.local/bin if not writable) / BINDIR env
  -d turns on debug logging
  [tag] is a tag from
  https://github.com/AlvinPlayz23/myagent/releases
  If tag is missing, then the latest release will be used.

Generated by godownloader https://github.com/goreleaser/godownloader (raw) - patched for tar.gz/zip archives

EOF
  exit 2
}
parse_args() {
  BINDIR=${BINDIR:-}
  # default fallback: /usr/local/bin if writable else ~/.local/bin
  if [ -z "$BINDIR" ]; then
    if [ -w /usr/local/bin ] 2>/dev/null; then
      BINDIR=/usr/local/bin
    else
      BINDIR=${HOME:-/tmp}/.local/bin
    fi
  fi
  while getopts "b:dh?x" arg; do
    case "$arg" in
      b) BINDIR="$OPTARG" ;;
      d) log_set_priority 10 ;;
      h | \?) usage "$0" ;;
      x) set -x ;;
    esac
  done
  shift $((OPTIND - 1))
  TAG=$1
}
tag_to_version() {
  if [ -z "${TAG}" ]; then
    log_info "checking GitHub for latest tag"
  else
    log_info "checking GitHub for tag '${TAG}'"
  fi
  REALTAG=$(github_release "$OWNER/$REPO" "${TAG}") && true
  if test -z "$REALTAG"; then
    log_crit "unable to find '${TAG}' - use 'latest' or see https://github.com/${PREFIX}/releases for details"
    exit 1
  fi
  TAG="$REALTAG"
  VERSION=${TAG#v}
}
# not used anymore - binary name patched below, kept for compat
adjust_binary() {
  if [ "$OS" = "windows" ]; then
    BINARY="${BINARY}.exe"
  fi
}
execute() {
  TMPDIR=$(mktemp -d)
  trap 'rm -rf "$TMPDIR"' EXIT INT TERM
  log_info "downloading ${TARBALL_URL}"
  http_download "${TMPDIR}/${TARBALL}" "$TARBALL_URL"
  log_info "downloading ${CHECKSUM_URL}"
  http_download "${TMPDIR}/checksums.txt" "$CHECKSUM_URL" || log_info "warning: could not download checksums.txt, skipping verification"
  if [ -f "${TMPDIR}/checksums.txt" ]; then
    hash_sha256_verify "${TMPDIR}/${TARBALL}" "${TMPDIR}/checksums.txt" || {
      log_err "checksum verification failed"
      exit 1
    }
    log_info "checksum verified"
  fi
  log_info "extracting ${TARBALL}"
  # diagnostic: show what we downloaded
  log_debug "archive file type: $(file "${TMPDIR}/${TARBALL}" 2>&1 | head -n 1)"
  log_debug "archive head magic: $(head -c 4 "${TMPDIR}/${TARBALL}" 2>&1 | od -An -tx1)"
  uname -m 1>&2 2>&1 | head -n 1 | xargs -I{} log_debug "uname -m: {}" 2>&1 || true
  # untar needs to cd into tmpdir
  (cd "$TMPDIR" && untar "${TARBALL}")
  log_debug "tmpdir contents after extract:"
  ls -lhR "$TMPDIR" 1>&2 2>&1 | head -n 40 || true
  # find the binary - exact name only, exclude archive itself (bug: myagent* matched myagent_v*.tar.gz -> gzip installed as binary -> exec format error)
  BIN_SRC=$(find "$TMPDIR" -maxdepth 3 -type f -name "${BINARY}" ! -name "*.tar.gz" ! -name "*.tgz" ! -name "*.zip" | head -n 1)
  if [ -z "$BIN_SRC" ] && [ "$OS" = "windows" ]; then
    BIN_SRC=$(find "$TMPDIR" -maxdepth 3 -type f -name "${BINARY}.exe" | head -n 1)
  fi
  if [ -z "$BIN_SRC" ]; then
    # fallback: top-level
    BIN_SRC="${TMPDIR}/${BINARY}"
    if [ "$OS" = "windows" ]; then
      BIN_SRC="${BIN_SRC}.exe"
    fi
  fi
  if [ ! -f "$BIN_SRC" ]; then
    log_crit "binary not found in archive (looked for ${BINARY})"
    log_crit "archive contents: $(tar -tzf "${TMPDIR}/${TARBALL}" 2>&1 | head -n 20)"
    ls -R "$TMPDIR" 1>&2 || true
    exit 1
  fi
  # sanity: refuse to install gzip/zip as binary (detect corrupted extract)
  if is_command file; then
    ftype=$(file "$BIN_SRC" 2>&1)
    log_debug "BIN_SRC file type: $ftype"
    case "$ftype" in
      *"gzip compressed"*|*"Zip archive"*) log_crit "extracted file is still an archive, not an ELF/Mach-O binary: $ftype"; exit 1 ;;
    esac
  else
    if head -c 4 "$BIN_SRC" 2>&1 | od -An -tx1 | grep -q "1f 8b"; then
      log_crit "extracted file has gzip magic 1f 8b, not ELF 7f 45 4c 46 - extraction failed"
      exit 1
    fi
  fi
  test ! -d "${BINDIR}" && install -d "${BINDIR}"
  install "${BIN_SRC}" "${BINDIR}/${BINARY}"
  chmod +x "${BINDIR}/${BINARY}"
  log_debug "installed file type: $(file "${BINDIR}/${BINARY}" 2>&1 | head -n 1)"
  log_debug "installed head magic: $(head -c 4 "${BINDIR}/${BINARY}" 2>&1 | od -An -tx1)"
  log_info "installed ${BINDIR}/${BINARY}"
  case ":$PATH:" in
    *":${BINDIR}:"*) ;;
    *) log_info "note: ${BINDIR} is not on PATH, add: export PATH=\"\$PATH:${BINDIR}\"" ;;
  esac
}

cat /dev/null <<EOF
------------------------------------------------------------------------
https://github.com/client9/shlib - portable posix shell functions
Public domain - http://unlicense.org
https://github.com/client9/shlib/blob/master/LICENSE.md
but credit (and pull requests) appreciated.
------------------------------------------------------------------------
EOF
is_command() {
  command -v "$1" >/dev/null
}
echoerr() {
  echo "$@" 1>&2
}
log_prefix() {
  echo "$0"
}
_logp=6
log_set_priority() {
  _logp="$1"
}
log_priority() {
  if test -z "$1"; then
    echo "$_logp"
    return
  fi
  [ "$1" -le "$_logp" ]
}
log_tag() {
  case $1 in
    0) echo "emerg" ;;
    1) echo "alert" ;;
    2) echo "crit" ;;
    3) echo "err" ;;
    4) echo "warning" ;;
    5) echo "notice" ;;
    6) echo "info" ;;
    7) echo "debug" ;;
    *) echo "$1" ;;
  esac
}
log_debug() {
  log_priority 7 || return 0
  echoerr "$(log_prefix)" "$(log_tag 7)" "$@"
}
log_info() {
  log_priority 6 || return 0
  echoerr "$(log_prefix)" "$(log_tag 6)" "$@"
}
log_err() {
  log_priority 3 || return 0
  echoerr "$(log_prefix)" "$(log_tag 3)" "$@"
}
log_crit() {
  log_priority 2 || return 0
  echoerr "$(log_prefix)" "$(log_tag 2)" "$@"
}
uname_os() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    cygwin_nt*) os="windows" ;;
    mingw*) os="windows" ;;
    msys_nt*) os="windows" ;;
  esac
  echo "$os"
}
uname_arch() {
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    x86) arch="386" ;;
    i686) arch="386" ;;
    i386) arch="386" ;;
    aarch64) arch="arm64" ;;
    armv5*) arch="armv5" ;;
    armv6*) arch="armv6" ;;
    armv7*) arch="armv7" ;;
  esac
  echo ${arch}
}
uname_os_check() {
  os=$(uname_os)
  case "$os" in
    darwin) return 0 ;;
    dragonfly) return 0 ;;
    freebsd) return 0 ;;
    linux) return 0 ;;
    android) return 0 ;;
    nacl) return 0 ;;
    netbsd) return 0 ;;
    openbsd) return 0 ;;
    plan9) return 0 ;;
    solaris) return 0 ;;
    windows) return 0 ;;
  esac
  log_crit "uname_os_check '$(uname -s)' got converted to '$os' which is not a GOOS value. Please file bug at https://github.com/client9/shlib"
  return 1
}
uname_arch_check() {
  arch=$(uname_arch)
  case "$arch" in
    386) return 0 ;;
    amd64) return 0 ;;
    arm64) return 0 ;;
    armv5) return 0 ;;
    armv6) return 0 ;;
    armv7) return 0 ;;
    ppc64) return 0 ;;
    ppc64le) return 0 ;;
    mips) return 0 ;;
    mipsle) return 0 ;;
    mips64) return 0 ;;
    mips64le) return 0 ;;
    s390x) return 0 ;;
    amd64p32) return 0 ;;
  esac
  log_crit "uname_arch_check '$(uname -m)' got converted to '$arch' which is not a GOARCH value.  Please file bug report at https://github.com/client9/shlib"
  return 1
}
untar() {
  tarball=$1
  case "${tarball}" in
    *.tar.gz | *.tgz) tar --no-same-owner -xzf "${tarball}" ;;
    *.tar) tar --no-same-owner -xf "${tarball}" ;;
    *.zip) unzip -o "${tarball}" ;;
    *)
      log_err "untar unknown archive format for ${tarball}"
      return 1
      ;;
  esac
}
http_download_curl() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -z "$header" ]; then
    code=$(curl -w '%{http_code}' -sL -o "$local_file" "$source_url")
  else
    code=$(curl -w '%{http_code}' -sL -H "$header" -o "$local_file" "$source_url")
  fi
  if [ "$code" != "200" ]; then
    log_debug "http_download_curl received HTTP status $code"
    return 1
  fi
  return 0
}
http_download_wget() {
  local_file=$1
  source_url=$2
  header=$3
  if [ -z "$header" ]; then
    wget -q -O "$local_file" "$source_url"
  else
    wget -q --header "$header" -O "$local_file" "$source_url"
  fi
}
http_download() {
  log_debug "http_download $2"
  if is_command curl; then
    http_download_curl "$@"
    return
  elif is_command wget; then
    http_download_wget "$@"
    return
  fi
  log_crit "http_download unable to find wget or curl"
  return 1
}
http_copy() {
  tmp=$(mktemp)
  http_download "${tmp}" "$1" "$2" || return 1
  body=$(cat "$tmp")
  rm -f "${tmp}"
  echo "$body"
}
github_release() {
  owner_repo=$1
  version=$2
  test -z "$version" && version="latest"
  giturl="https://github.com/${owner_repo}/releases/${version}"
  json=$(http_copy "$giturl" "Accept:application/json")
  test -z "$json" && return 1
  version=$(echo "$json" | tr -s '\n' ' ' | sed 's/.*"tag_name":"//' | sed 's/".*//')
  test -z "$version" && return 1
  echo "$version"
}
hash_sha256() {
  TARGET=${1:-/dev/stdin}
  if is_command gsha256sum; then
    hash=$(gsha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command sha256sum; then
    hash=$(sha256sum "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command shasum; then
    hash=$(shasum -a 256 "$TARGET" 2>/dev/null) || return 1
    echo "$hash" | cut -d ' ' -f 1
  elif is_command openssl; then
    hash=$(openssl -dst openssl dgst -sha256 "$TARGET") || return 1
    echo "$hash" | cut -d ' ' -f a
  else
    log_crit "hash_sha256 unable to find command to compute sha-256 hash"
    return 1
  fi
}
hash_sha256_verify() {
  TARGET=$1
  checksums=$2
  if [ -z "$checksums" ]; then
    log_err "hash_sha256_verify checksum file not specified in arg2"
    return 1
  fi
  BASENAME=${TARGET##*/}
  want=$(grep "${BASENAME}" "${checksums}" 2>/dev/null | tr '\t' ' ' | cut -d ' ' -f 1)
  if [ -z "$want" ]; then
    log_err "hash_sha256_verify unable to find checksum for '${TARGET}' in '${checksums}'"
    return 1
  fi
  got=$(hash_sha256 "$TARGET")
  if [ "$want" != "$got" ]; then
    log_err "hash_sha256_verify checksum for '$TARGET' did not verify ${want} vs $got"
    return 1
  fi
}
cat /dev/null <<EOF
------------------------------------------------------------------------
End of functions from https://github.com/client9/shlib
------------------------------------------------------------------------
EOF

OWNER=AlvinPlayz23
REPO="myagent"
BINARY=myagent
PREFIX="$OWNER/$REPO"
log_prefix() {
        echo "$PREFIX"
}
OS=$(uname_os)
ARCH=$(uname_arch)
GITHUB_DOWNLOAD=https://github.com/${OWNER}/${REPO}/releases/download

uname_os_check "$OS"
uname_arch_check "$ARCH"

parse_args "$@"

tag_to_version

log_info "found version ${VERSION} for ${TAG}/${OS}/${ARCH}"

# patched for goreleaser archives: myagent_<version>_<os>_<arch>.tar.gz / .zip
# matches .goreleaser.yaml name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
if [ "$OS" = "windows" ]; then
  TARBALL="myagent_${TAG}_${OS}_${ARCH}.zip"
else
  TARBALL="myagent_${TAG}_${OS}_${ARCH}.tar.gz"
fi
TARBALL_URL=${GITHUB_DOWNLOAD}/${TAG}/${TARBALL}
CHECKSUM_URL=${GITHUB_DOWNLOAD}/${TAG}/checksums.txt

# adjust binary name for windows
if [ "$OS" = "windows" ]; then
  BINARY="${BINARY}.exe"
fi

execute
