// Package compaction implements context-window compaction for the agent loop.
//
// Ported from pi packages/agent/src/harness/compaction/. When the conversation
// nears the configured context window, older history is summarized into a
// structured summary (generated by the same provider/model with a dedicated
// system prompt) and replaced by [summary message] + [recent messages]. The
// summary is generated from a serialized text form of the conversation so the
// model cannot "continue" it; tool results are truncated during serialization.
package compaction

// ContextWindow is the harness-level context window, in tokens. Per the
// myagent plan: a single fixed harness limit.
const ContextWindow = 256_000

// Settings controls when compaction triggers and how much recent context is
// preserved. Ported from pi's CompactionSettings.
type Settings struct {
	Enabled          bool
	ReserveTokens    int // room reserved for the LLM response + summary prompt
	KeepRecentTokens int // approximate recent-context tokens kept verbatim
}

// DefaultSettings are the harness defaults. ReserveTokens=26000 triggers
// compaction at ContextWindow - ReserveTokens = 230000 tokens.
// KeepRecentTokens mirrors pi's default (20000).
var DefaultSettings = Settings{
	Enabled:          true,
	ReserveTokens:    26_000,
	KeepRecentTokens: 20_000,
}

// ShouldCompact reports whether the current context token count is high enough
// to trigger auto-compaction. Ported from pi shouldCompact: triggers when
// contextTokens > contextWindow - reserveTokens.
func ShouldCompact(contextTokens, contextWindow int, s Settings) bool {
	if !s.Enabled {
		return false
	}
	return contextTokens > contextWindow-s.ReserveTokens
}
